# Generated by Django 5.1.1 on 2024-10-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='username_null', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
