# Generated by Django 5.1.1 on 2024-10-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_shipping_option_product_freeshipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Unisex', 'Unisex')], default='Unisex', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.JSONField(blank=True, default=list, verbose_name=models.FloatField()),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
