# Generated by Django 5.1.1 on 2024-10-02 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_sizes_remove_product_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discountPrice',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10000000)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_option',
            field=models.CharField(max_length=10, verbose_name=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000000)]),
        ),
    ]
