# Generated by Django 5.1.1 on 2024-10-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_discountprice_alter_order_shipping_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bank_transfer_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_option',
            field=models.CharField(max_length=10),
        ),
    ]
